# This rule is not used by the project np-tester itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over neptuneplus.polimi.it.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: np-tester
    app.kubernetes.io/managed-by: kustomize
  name: neptuneplus-dependencygraph-admin-role
rules:
- apiGroups:
  - neptuneplus.polimi.it
  resources:
  - dependencygraphs
  verbs:
  - '*'
- apiGroups:
  - neptuneplus.polimi.it
  resources:
  - dependencygraphs/status
  verbs:
  - get
