# This rule is not used by the project np-tester itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the neptuneplus.polimi.it.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: np-tester
    app.kubernetes.io/managed-by: kustomize
  name: neptuneplus-dependencygraph-editor-role
rules:
- apiGroups:
  - neptuneplus.polimi.it
  resources:
  - dependencygraphs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - neptuneplus.polimi.it
  resources:
  - dependencygraphs/status
  verbs:
  - get
