apiVersion: apps/v1
kind: Deployment
metadata:
  name: np-dag-expo-deployment
  namespace: kube-system
  labels:
    app: np-dag-expo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: np-dag-expo
  template:
    metadata:
      labels:
        app: np-dag-expo
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      automountServiceAccountToken: true
      serviceAccountName: np-tester-manager-sa
      containers:
        - name: np-dag-expo-container
          image: itspeetah/np-dag-expo:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # Assuming the application listens on port 8080
          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "128Mi"
