apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: np-tester
    app.kubernetes.io/managed-by: kustomize
  name: np-tester-manager-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: np-tester:manager
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - neptuneplus.polimi.it
    resources:
      - dependencygraphs
      - dependencygraphs/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - systemautoscaler.polimi.it
    resources:
      - podscales
      - podscales/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - custom.metrics.k8s.io
    resources:
      - pods/response_time
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: np-tester-watcher-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: np-tester:manager
subjects:
  - kind: ServiceAccount
    name: np-tester-manager-sa
    namespace: kube-system
    apiGroup: ""
