apiVersion: neptuneplus.polimi.it/v1alpha1
kind: DependencyGraph
metadata:
  labels:
    app.kubernetes.io/name: np-tester
    app.kubernetes.io/managed-by: kustomize
  name: dependencygraph-sample
spec:
  # TODO(user): Add fields here
